version: '3.4'

services:
  api:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    container_name: schedules-api
    depends_on:
      - db

  db:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=schedules
    ports:
      - '3306:3306'
    volumes:
      - .mysql:/var/lib/mysql
    container_name: schedules-db
